[book]
authors = ["Tab Liu"]
language = "zh-CN"
multilingual = false
src = "src"
title = "个人博客入口"

description = "tab liu"

[rust]
edition = "2021"

[output.html]
no-section-label = true # 左边不显示序号,如"1.1", "1.2.1"
# 右上角的github图标链接
git-repository-url = "https://github.com/tab-liu/tab-liu.github.io"
git-repository-icon = "fa-github"
additional-css = ["theme/style.css"]
additional-js = ["theme/sidebar.js"]
mathjax-support = true                                              # 数学公式支持


[preprocessor.katex]
after = ["links"]
