name: GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v4.0.0
            - uses: drmingdrmer/mdbook-full@main

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v1.2.0
              with:
                  mdbook-version: "latest"

            # 使用katex，以支持常规的$行内公式$
            # - name: Setup mdbook-katex
            #   uses: magicgh/mdbook-katex-action@v1.1.0
            #   with:
            #       version: "latest"

            - run: mdbook build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.9.3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./book
                  cname: tabliu.top
