name: GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v1
              with:
                  mdbook-version: "latest"
                  # mdbook-version: "0.4.8"

            # 使用katex，以支持常规的$行内公式$
            - name: Setup mdbook-katex
              uses: magicgh/mdbook-katex-action@v1
              with:
                  version: "latest"

            - run: mdbook build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./book
                  cname: tabliu.top
