name: GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v4.0.0

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v1.2.0
              with:
                  mdbook-version: "latest"

            # 使用katex，以支持常规的$行内公式$
            - name: Install mdbook-katex
              run: |
                  curl -Lo mdbook-katex.tar.gz https://github.com/lzanini/mdbook-katex/releases/download/v0.5.7/mdbook-katex-v0.5.7-x86_64-unknown-linux-gnu.tar.gz
                  tar xzf mdbook-katex.tar.gz
                  mv mdbook-katex /home/runner/toolbin/mdbook-katex

            # - name: Setup mdbook-katex
            #   uses: magicgh/mdbook-katex-action@v1.1.0
            #   run: |
            #       curl -L -o mdbook-katex.tar.gz https://github.com/huhu/md
            # #   with:
            # #       version: "latest"

            - run: mdbook build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.9.3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./book
                  cname: tabliu.top
